<?php require './templates/header.phtml';

//MANEJAR EL ERROR DE QUE SI SE QUIERE AGG UN CAP Y TIENE EL MISMO CHAPTERNUMBER Y LO MISMO CON SEASONCHAPTER
//MANEJAR ERRORESSS
 
 
 ?>

<h1>SEARCH CHAPTER</h1>

<ul>
    <?php foreach($chapters as $chapter): ?>
        <li>
            <div>
                <p><?=$chapter->chapterNumber?> | Name: <?=$chapter->name?> | Description: <?=$chapter->description?> </p>
            </div>
            <div class="actions">
                <a href="chapterOfSeason/<?=$chapter->season_id?>" type="button" class='btn btn-danger ml-auto'>Season</a>
            </div> 
        </li>
    <?php endforeach ?>
</ul>


