<?php require './templates/header.phtml'; ?>

<h1>SEARCH CHAPTER</h1>

<ul>
    <?php foreach($chapters as $chapter): ?>
        <li>
            <div>
                <p><?=$chapter->chapterNumber?> | Name: <?=$chapter->name?> | Description: <?=$chapter->description?> </p>
            </div>
            <div class="actions">
                <a href="chapterOfSeason/<?=$chapter->season_id?>" type="button" class='btn btn-danger ml-auto'>Show more</a>
            </div> 
        </li>
    <?php endforeach ?>
</ul>


