<?php 
require './templates/header.phtml';
?>
<div class="forms-editorSection">
<form  id = "formSeasons"action="addSeason" method ="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Season Number</label>
                <input required type="number" name = "seasonNumber" class="form-control">
            </div>
        </div>
        <div class= "col-3">
            <div class= "form-group">
                <label>Release Year</label>
                <input required type="number" name = "releaseYear" class="form-control">
            </div>
        </div>
    </div>
    <div class="row">
        <div class= "col-5">
            <div class="form-group">
                <label>Director</label>
                <input required type="text" name = "director" class="form-control">
            </div>
        </div>
        <div class= "col-7">
            <div class="form-group">
                <label>Recording City</label>
                <input required type="text" name="recordingCity" class="form-control">
            </div>
        </div>
    </div>    
        <div class="col-12">
            <div class="form-group">
                <label>Category Genre</label>
                <input required type="text" name= "categoryGenre" class="form-control">
            </div>
        </div>
    <button type = "submit" class="btn btn-primary mt-2">Add season</button>
</form>



<form id = "formChapter"action="addChapter" method="POST">
    <div class="form-group">
        <label>Add season</label>
        <select required name="season_id_fk" class="form-control">
            <?php foreach($seasons as $season): ?>
            <option value="season_id_fk"><?= $season->season_id?></option>
            <?php endforeach ?>
        </select>
    </div>
    <div class="form-group">
        <label>Name</label>
        <input required type="text" name= "name" class="form-control">
    </div>
    <div class="form-group">
            <label>Description</label>
            <textarea required name = "description" class="form-control" rows="3"></textarea>
    </div>

    <button type= "submit" class="btn btn-primary mt-2">Add chapter</button>
</form>
</div>
<ul class="list-group">
    <?php foreach($seasons as $season): ?>
        <li class="list-group-item item-form">
            <div>
                <b><?= $season->seasonNumber?>| <?=$season->director?> | <?=$season->recordingCity ?> | <?=$season->categoryGenre?> | (Release Year: <?= $season->releaseYear ?>)</b>
            </div>
            <div class= "actions">
                <a href="deleteSeason/<?=$season->season_id?>" type="button" class='btn btn-danger ml-auto'>Delete</a>
            </div>
        </li>
    <?php endforeach?>
</ul>

<ul class="list-group">
    <?php foreach($chapters as $chapter) : ?>
        <li class="list-group-item item-form">
        <div>
            <b><?= $chapter->name ?> | Season: <?= $chapter->season_id_fk?> |  <?=$chapter->description?></b>
        </div>
        <div class= "actions">
            <a href="deleteChapter/<?= $chapter->chapter_id ?>" type="button" class='btn btn-danger ml-auto'>Delete</a>
            <a href="showEdit/<?= $chapter->chapter_id?>" type="button" class='btn btn-danger ml-auto'>Edit</a>
        </div>
        </li>
    <?php endforeach ?>
</ul>

<?php require './templates/footer.phtml'?>