<?php
require 'templates/header.phtml';?>

<form action="editChapter/<?=$id?>" method="POST" class="my-4">
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <label>Name</label>
                <input name="name" type="text"  class="form-control"> 
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <label>Description</label>
                <input name="description" type="text"  class="form-control">
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="form-group">
            <label>Season</label>
            <select name="season_id_fk" class="form-control">
                <?php foreach ($seasons as $season): ?> 
                    <option value="season_id"><?= $season->season_id ?></option>    
                <?php endforeach ?>    
            </select>
        </div>
    </div>

    <button type="submit" class="btn btn-primary mt-2" >Edit</button> 
    
</form>
<?php
require 'templates/footer.phtml';
