<?php 
require './templates/header.phtml' ;
//seasonNumber, relaseYear, director, recordingCity, recordingGenre
//season_id, name, description
?>
<div class="forms-editorSection">
<form  id = "formSeasons"action="addSeason" method ="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Season Number</label>
                <input required type="number" name = "seasonNumber" class="form-control">
            </div>
        </div>
        <div class= "col-3">
            <div class= "form-group">
                <label>release Year</label>
                <input required type="number" name = "releaseYear" class="form-control">
            </div>
        </div>
    </div>
    <div class="row">
        <div class= "col-5">
            <div class="form-group">
                <label>Director</label>
                <input required type="text" name = "director" class="form-control">
            </div>
        </div>
        <div class= "col-7">
            <div class="form-group">
                <label>Recording City</label>
                <input required type="text" name="recordingCity" class="form-control">
            </div>
        </div>
    </div>    
        <div class="col-12">
            <div class="form-group">
                <label>Category Genre</label>
                <input required type="text" name= "categoryGenre" class="form-control">
            </div>
        </div>
    <button type = "submit" class="btn btn-primary mt-2">Add season</button>
</form>

<form id = "formChapter"action="addChapter" method="POST">
    <div class="form-group">
        <label>Add season</label>
        <select required name="selectSeason" class="form-control">
            <?php foreach($seasons as $season): ?>
            <option value="season">Season <?= $season->seasonNumber ?></option>
            <?php endforeach ?>
        </select>
    </div>
    <div class="form-group">
        <label>Name</label>
        <input required type="text" name= "name" class="form-control">
    </div>
    <div class="form-group">
            <label>Description</label>
            <textarea required name = "description" class="form-control" rows="3"></textarea>
    </div>

    <button type= "submit" class="btn btn-primary mt-2">Add chapter</button>
</form>
</div>
<ul class="list-group">
    <?php foreach($seasons as $season): ?>
        <li class="list-group-item item-season">
            <div>
                <b><?= $season->seasonNumber?></b>| <?=$season->director?> | (Release Year: <?= $season->releaseYear ?>)
            </div>
            <div class= "actions">
            <a href="delete/<?= $season->season_id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
            </div>
        </li>
    <?php endforeach?>
</ul>
<ul class="list-chapters">
    <?php foreach($chapters as $chapter) : ?>
        <li class="list-group-item item-season">
        <div>
        <b><?= $chapter->name ?> || <?= $chapter->description ?> || Temporada: <?= $chapter->season_id_fk?> </b>
        <div class= "actions">
            <a href="delete/<?= $season->season_id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
            </div>
            </li>
    <?php endforeach ?>
</ul>

<?php require './templates/footer.phtml'?>